### PR TITLE
Render bin

### PR DESCRIPTION
**Pull request by meson10**
Fixes #5

### CODE REVIEW

**Comment by meson10** [comment]
Damn. Something changed in master in past few days because of which this is failing. Will fix and push.

**Comment by datastax-meson10** [comment]
@markbates Thank you for the feedback. I apologize for few obvious things that were missed. I will send you an updated PR that tackles all 4.

**Comment by Dexus** [comment]
Never updated... very nice... tzzz...

**Comment by markbates** [comment]
Closing due to lack of progress.

**Pull request closed without merging**
