### PR TITLE
Fix if condition if one of the nodes is undefined while the operator is Or and the other node is true

### PR DESCRIPTION
**Pull request by Mido-sys**
Fix for issue [#157 ](https://github.com/gobuffalo/plush/issues/157)

### CODE REVIEW

**Comment by Mido-sys** [comment]
@sio4, just a kind reminder :)

**Comment by Mido-sys** [comment]
@sio4, no worries!! Thanks, the Timezone difference makes it hard :)

**Review by sio4 — APPROVED** [review]
Thanks for your contribution @Mido-sys!

It looks good to me, but it also seems to be improved some more points in the function and the other test case. I will take care of that part after mering this PR.

Thanks!

**Comment by sio4** [comment]
Hi @Mido-sys,

FYI, I found some issues (side effects) on this PR while I review the method to improve the efficiency, and filed a PR (#166) to fix the issue. The main difference between those two approaches is that yours is more focused on the value, but mine is focused on the operations.

Just wanted to let you know about the change!

**Pull request merged**
