### PR TITLE
[FAILING] failing test to show that early return arguments do not stop execution of functions

### PR DESCRIPTION
**Pull request by matryer**
NOTE: THIS PR CAUSES THE TESTS TO FAIL

Given this plush code:

```
let print = fn(obj) {
	if (obj.Secret) {
		return "**********"
	}
	return obj.String
}
```

If I pass an `obj` that looks like this: `{Secret: true, String: "your royal highness"}`, I would expect the `if` branch to trigger and `"**********"` to get returned.

However, with this:

```
You are: <%= print(data) %>.
```

I get:

```
You are: your royal highness.
```

Instead of: 

```
You are: **********.
```

### CODE REVIEW

**Comment by matryer** [comment]
NOTE: Returning `s` (instead of `nil`) in `evalStatement` regardless of the type (i.e. even if it's not `ast.Printable` or `template.HTML` causes _both_ returns to be printed.

**Comment by matryer** [comment]
@stanislas-m Do you think this would be easy to fix?

**Comment by stanislas-m** [comment]
@matryer I'll take a look. :) My week was pretty busy, but this one is on my todo list.

**Comment by paganotoni** [comment]
#127 takes care of this.

**Pull request closed without merging**
